<#
.SYNOPSIS
    Exports the Active Directory Sites & Services topology for divestiture discovery.

.DESCRIPTION
    Read-only discovery of the replication topology a new-forest divestiture needs to reproduce:
      - Sites: name, associated subnets, and the Domain Controllers located in each site.
      - Subnets: CIDR, the site each maps to, and location - the subnet-to-site mapping that the
        SoW flags as an explicit design artefact for the remote sites.
      - Site links: name, cost, replication interval, and member sites.
      - Inter-site connections: from/to server and whether the connection is automatically or
        manually generated (KCC vs. manual).

    Live data is read from the AD configuration partition with the ActiveDirectory module; row
    shaping is separated so it is unit-testable with mock data. The script makes no changes.

.PARAMETER Server
    Optional Domain Controller / AD Web Services server to target for the queries.

.PARAMETER Credential
    Optional credential for the AD queries.

.PARAMETER OutputFolder
    Optional folder for the CSV outputs (Sites.csv, Subnets.csv, SiteLinks.csv, SiteConnections.csv).
    If omitted, results are only written to the pipeline/table.

.EXAMPLE
    .\Export-AdSiteTopologyInventory.ps1 -OutputFolder .\SiteTopology
#>

[CmdletBinding()]
param(
    [string]$Server = '',
    [pscredential]$Credential,
    [string]$OutputFolder = ''
)

$ErrorActionPreference = 'Stop'

function Get-RdnFromDistinguishedName {
    param([AllowNull()] [string]$DistinguishedName)

    if ([string]::IsNullOrWhiteSpace($DistinguishedName)) { return '' }
    $first = ($DistinguishedName -split '(?<!\\),')[0]
    return ($first -replace '^[A-Za-z]+=', '')
}

function New-SiteRow {
    param(
        [Parameter(Mandatory = $true)] $Site,
        [Parameter(Mandatory = $true)] [AllowNull()] $SubnetNames,
        [Parameter(Mandatory = $true)] [AllowNull()] $DomainControllers
    )

    $subnetList = @($SubnetNames | Where-Object { $_ })
    $dcList = @($DomainControllers | Where-Object { $_ })
    return [pscustomobject]@{
        SiteName          = [string]$Site.Name
        Subnets           = ($subnetList -join ';')
        SubnetCount       = $subnetList.Count
        DomainControllers = ($dcList -join ';')
        DcCount           = $dcList.Count
    }
}

function New-SubnetRow {
    param([Parameter(Mandatory = $true)] $Subnet)

    return [pscustomobject]@{
        Subnet   = [string]$Subnet.Name
        Site     = (Get-RdnFromDistinguishedName -DistinguishedName ([string]$Subnet.Site))
        Location = [string]$Subnet.Location
    }
}

function New-SiteLinkRow {
    param([Parameter(Mandatory = $true)] $SiteLink)

    return [pscustomobject]@{
        SiteLinkName            = [string]$SiteLink.Name
        Cost                    = [int]$SiteLink.Cost
        ReplicationIntervalMins = [int]$SiteLink.ReplicationFrequencyInMinutes
        Sites                   = (@($SiteLink.SiteList | ForEach-Object { Get-RdnFromDistinguishedName -DistinguishedName ([string]$_) }) -join ';')
    }
}

function New-SiteConnectionRow {
    param([Parameter(Mandatory = $true)] $Connection)

    return [pscustomobject]@{
        ConnectionName     = [string]$Connection.Name
        FromServer         = (Get-RdnFromDistinguishedName -DistinguishedName ([string]$Connection.FromServer))
        EnabledConnection  = [bool]$Connection.EnabledConnection
        AutoGenerated      = [bool]$Connection.AutoGenerated
    }
}

function Get-AdSiteTopologyFacts {
    param(
        [string]$Server = '',
        [pscredential]$Credential
    )

    Import-Module ActiveDirectory -ErrorAction Stop
    $adParams = @{}
    if (-not [string]::IsNullOrWhiteSpace($Server)) { $adParams.Server = $Server }
    if ($Credential) { $adParams.Credential = $Credential }

    $configNc = (Get-ADRootDSE @adParams).configurationNamingContext

    $sites = @(Get-ADReplicationSite -Filter * @adParams)
    $subnets = @(Get-ADReplicationSubnet -Filter * -Properties Site, Location @adParams)
    $siteLinks = @(Get-ADReplicationSiteLink -Filter * -Properties SiteList, Cost, ReplicationFrequencyInMinutes @adParams)

    $connections = @()
    try {
        $connectionParams = $adParams.Clone()
        $connectionParams['SearchBase'] = "CN=Sites,$configNc"
        $connectionParams['Filter'] = { objectClass -eq 'nTDSConnection' }
        $connectionParams['Properties'] = @('fromServer','enabledConnection','options')
        foreach ($connection in @(Get-ADObject @connectionParams)) {
            $connections += [pscustomobject]@{
                Name              = $connection.Name
                FromServer        = $connection.fromServer
                EnabledConnection = [bool]$connection.enabledConnection
                # options bit 0 set = KCC-generated (auto); cleared/absent = manual.
                AutoGenerated     = (($null -ne $connection.options) -and (([int]$connection.options -band 1) -ne 0))
            }
        }
    } catch { }

    # Map DCs to sites for the site rows.
    $dcsBySite = @{}
    try {
        foreach ($dc in @(Get-ADDomainController -Filter * @adParams)) {
            $siteName = [string]$dc.Site
            if (-not $dcsBySite.ContainsKey($siteName)) { $dcsBySite[$siteName] = [System.Collections.Generic.List[string]]::new() }
            $dcsBySite[$siteName].Add([string]$dc.HostName)
        }
    } catch { }

    return @{
        Sites        = $sites
        Subnets      = $subnets
        SiteLinks    = $siteLinks
        Connections  = $connections
        DcsBySite    = $dcsBySite
    }
}

function Get-AdSiteTopologyInventory {
    param([Parameter(Mandatory = $true)] $Facts)

    $subnetsBySite = @{}
    foreach ($subnet in @($Facts.Subnets)) {
        $siteName = Get-RdnFromDistinguishedName -DistinguishedName ([string]$subnet.Site)
        if (-not $subnetsBySite.ContainsKey($siteName)) { $subnetsBySite[$siteName] = [System.Collections.Generic.List[string]]::new() }
        $subnetsBySite[$siteName].Add([string]$subnet.Name)
    }

    $dcsBySite = $Facts.DcsBySite
    if (-not $dcsBySite) { $dcsBySite = @{} }

    $siteRows = @(@($Facts.Sites) | ForEach-Object {
        $siteName = [string]$_.Name
        $subnetNames = if ($subnetsBySite.ContainsKey($siteName)) { $subnetsBySite[$siteName] } else { @() }
        $dcNames = if ($dcsBySite.ContainsKey($siteName)) { $dcsBySite[$siteName] } else { @() }
        New-SiteRow -Site $_ -SubnetNames $subnetNames -DomainControllers $dcNames
    })

    return @{
        Sites       = $siteRows
        Subnets     = @(@($Facts.Subnets) | ForEach-Object { New-SubnetRow -Subnet $_ })
        SiteLinks   = @(@($Facts.SiteLinks) | ForEach-Object { New-SiteLinkRow -SiteLink $_ })
        Connections = @(@($Facts.Connections) | ForEach-Object { New-SiteConnectionRow -Connection $_ })
    }
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
Write-Host 'Collecting AD Sites & Services topology...' -ForegroundColor Cyan
$facts = Get-AdSiteTopologyFacts -Server $Server -Credential $Credential
$inventory = Get-AdSiteTopologyInventory -Facts $facts

Write-Host "`n=== Sites ($(@($inventory.Sites).Count)) ===" -ForegroundColor Yellow
$inventory.Sites | Format-Table SiteName, SubnetCount, DcCount, Subnets -AutoSize
Write-Host "=== Subnets ($(@($inventory.Subnets).Count)) ===" -ForegroundColor Yellow
$inventory.Subnets | Format-Table -AutoSize
Write-Host "=== Site Links ($(@($inventory.SiteLinks).Count)) ===" -ForegroundColor Yellow
$inventory.SiteLinks | Format-Table -AutoSize

if (-not [string]::IsNullOrWhiteSpace($OutputFolder)) {
    if (-not (Test-Path -Path $OutputFolder)) { New-Item -Path $OutputFolder -ItemType Directory -Force | Out-Null }
    $inventory.Sites | Export-Csv -Path (Join-Path $OutputFolder 'Sites.csv') -NoTypeInformation -Encoding UTF8
    $inventory.Subnets | Export-Csv -Path (Join-Path $OutputFolder 'Subnets.csv') -NoTypeInformation -Encoding UTF8
    $inventory.SiteLinks | Export-Csv -Path (Join-Path $OutputFolder 'SiteLinks.csv') -NoTypeInformation -Encoding UTF8
    $inventory.Connections | Export-Csv -Path (Join-Path $OutputFolder 'SiteConnections.csv') -NoTypeInformation -Encoding UTF8
    Write-Host ("Reports exported to: {0}" -f $OutputFolder) -ForegroundColor Green
}
