#Requires -Version 7
$ErrorActionPreference = 'Stop'

$script:ScriptPath = Join-Path $PSScriptRoot '..' 'Export-AdSiteTopologyInventory.ps1'
$script:Failures = [System.Collections.Generic.List[string]]::new()
$script:Passes = 0

function Get-ScriptAst {
    $tokens = $null
    $parseErrors = $null
    $ast = [System.Management.Automation.Language.Parser]::ParseFile($script:ScriptPath, [ref]$tokens, [ref]$parseErrors)
    if ($parseErrors.Count -gt 0) {
        throw "Parse errors in $($script:ScriptPath): $($parseErrors[0].Message)"
    }
    return $ast
}

function Import-ScriptFunctions {
    $ast = Get-ScriptAst
    $functions = $ast.FindAll({ param($node) $node -is [System.Management.Automation.Language.FunctionDefinitionAst] }, $true)
    foreach ($functionAst in $functions) {
        . ([scriptblock]::Create($functionAst.Extent.Text))
    }
}

function Assert-True {
    param(
        [Parameter(Mandatory = $true)] [bool]$Condition,
        [Parameter(Mandatory = $true)] [string]$Name
    )
    if ($Condition) {
        $script:Passes++
        Write-Host "PASS $Name" -ForegroundColor Green
    }
    else {
        $script:Failures.Add($Name) | Out-Null
        Write-Host "FAIL $Name" -ForegroundColor Red
    }
}

. Import-ScriptFunctions

function Test-RequiredFunctionsExist {
    $ast = Get-ScriptAst
    $functionNames = @($ast.FindAll({ param($node) $node -is [System.Management.Automation.Language.FunctionDefinitionAst] }, $true) | ForEach-Object Name)
    foreach ($name in @('Get-RdnFromDistinguishedName','New-SiteRow','New-SubnetRow','New-SiteLinkRow','New-SiteConnectionRow','Get-AdSiteTopologyFacts','Get-AdSiteTopologyInventory')) {
        Assert-True -Condition ($functionNames -contains $name) -Name "Function exists: $name"
    }
}
Test-RequiredFunctionsExist

function Test-ReadOnly {
    $scriptText = Get-Content -Path $script:ScriptPath -Raw
    Assert-True -Condition ($scriptText -notmatch 'Set-AD' -and $scriptText -notmatch 'Remove-AD' -and $scriptText -notmatch 'New-ADReplication') -Name 'Script performs no AD write operations'
    Assert-True -Condition ($scriptText -match 'Get-ADReplicationSite') -Name 'Site query is present'
    Assert-True -Condition ($scriptText -match 'Get-ADReplicationSubnet') -Name 'Subnet query is present'
}
Test-ReadOnly

function Test-RdnParsing {
    Assert-True -Condition ((Get-RdnFromDistinguishedName -DistinguishedName 'CN=Azure-AE,CN=Sites,CN=Configuration,DC=contoso,DC=com') -eq 'Azure-AE') -Name 'RDN parsed from a site DN'
    Assert-True -Condition ((Get-RdnFromDistinguishedName -DistinguishedName '') -eq '') -Name 'Empty DN returns empty string'
}
Test-RdnParsing

function New-MockTopologyFacts {
    $dcsBySite = @{
        'Azure-AE' = [System.Collections.Generic.List[string]]@('dc01.contoso.com','dc02.contoso.com')
        'Site-Perth' = [System.Collections.Generic.List[string]]@('dc03.contoso.com')
    }
    return @{
        Sites = @(
            [pscustomobject]@{ Name = 'Azure-AE' },
            [pscustomobject]@{ Name = 'Site-Perth' },
            [pscustomobject]@{ Name = 'Site-NoSubnet' }
        )
        Subnets = @(
            [pscustomobject]@{ Name = '10.0.0.0/24'; Site = 'CN=Azure-AE,CN=Sites,CN=Configuration,DC=contoso,DC=com'; Location = 'Azure UAE' },
            [pscustomobject]@{ Name = '10.1.0.0/24'; Site = 'CN=Site-Perth,CN=Sites,CN=Configuration,DC=contoso,DC=com'; Location = 'Perth' },
            [pscustomobject]@{ Name = '10.0.1.0/24'; Site = 'CN=Azure-AE,CN=Sites,CN=Configuration,DC=contoso,DC=com'; Location = 'Azure UAE' }
        )
        SiteLinks = @(
            [pscustomobject]@{ Name = 'Azure-Perth'; Cost = 100; ReplicationFrequencyInMinutes = 15; SiteList = @('CN=Azure-AE,CN=Sites,CN=Configuration,DC=contoso,DC=com','CN=Site-Perth,CN=Sites,CN=Configuration,DC=contoso,DC=com') }
        )
        Connections = @(
            [pscustomobject]@{ Name = '<automatically generated>'; FromServer = 'CN=NTDS Settings,CN=DC01,CN=Servers,CN=Azure-AE,CN=Sites,CN=Configuration,DC=contoso,DC=com'; EnabledConnection = $true; AutoGenerated = $true }
        )
        DcsBySite = $dcsBySite
    }
}

function Test-InventoryShaping {
    $inventory = Get-AdSiteTopologyInventory -Facts (New-MockTopologyFacts)

    Assert-True -Condition (@($inventory.Sites).Count -eq 3) -Name 'One row per site'
    $azure = $inventory.Sites | Where-Object SiteName -eq 'Azure-AE'
    Assert-True -Condition ($azure.SubnetCount -eq 2 -and $azure.Subnets -match '10.0.0.0/24' -and $azure.Subnets -match '10.0.1.0/24') -Name 'Site aggregates its subnets'
    Assert-True -Condition ($azure.DcCount -eq 2) -Name 'Site aggregates its DCs'
    $noSubnet = $inventory.Sites | Where-Object SiteName -eq 'Site-NoSubnet'
    Assert-True -Condition ($noSubnet.SubnetCount -eq 0 -and $noSubnet.DcCount -eq 0) -Name 'Site with no subnets/DCs shapes to zero counts'

    $subnetRow = $inventory.Subnets | Where-Object Subnet -eq '10.1.0.0/24'
    Assert-True -Condition ($subnetRow.Site -eq 'Site-Perth' -and $subnetRow.Location -eq 'Perth') -Name 'Subnet maps to its site RDN and location'

    Assert-True -Condition ($inventory.SiteLinks[0].Sites -eq 'Azure-AE;Site-Perth' -and $inventory.SiteLinks[0].Cost -eq 100) -Name 'Site link resolves member site names and cost'
    Assert-True -Condition ($inventory.Connections[0].FromServer -eq 'NTDS Settings' -and $inventory.Connections[0].AutoGenerated -eq $true) -Name 'Connection shaping resolves from-server and auto-generated flag'
}
Test-InventoryShaping

if ($script:Failures.Count -gt 0) {
    Write-Host "$($script:Failures.Count) check(s) failed." -ForegroundColor Red
    exit 1
}
Write-Host "All $($script:Passes) checks passed." -ForegroundColor Green
exit 0
